"""
Property based tests for the resolve -> extract -> write -> resolve round
trip. In contrast to the hand written cases in `test_extractor.py` the
molecules here are generated by hypothesis, which also generates the node
and fragid permutations, so a failure comes with a replayable example
instead of showing up as an occasional red CI run.

Every property builds its reference molecule from a CGsmiles string in
which each meta edge carries its own `[>n]`/`[<n]` label pair. Such a
string admits exactly one pairing of the bonding descriptors, so the
reference does not depend on the order in which the resolver happens to
walk the meta edges.
"""
from collections import Counter
import networkx as nx
import pytest
from hypothesis import HealthCheck, Phase, given, note, settings
from hypothesis import strategies as st

import cgsmiles
from cgsmiles.extractor import MoleculeFragmentExtractor
from cgsmiles.read_cgsmiles import read_cgsmiles
from cgsmiles.write_cgsmiles import write_cgsmiles, write_cgsmiles_graph

# largest number of bonding sites any of the fragment bodies below offers;
# the generated meta graphs are capped at this degree
MAX_SITES = 3

# fragment bodies keyed by the number of bonding sites they provide. The
# `{}` are filled with bonding descriptors; a site that is not used by any
# meta edge is filled with '' and simply becomes a hydrogen on resolve.
FRAGMENT_BODIES = {
    1: ("{}C", "{}O", "{}N", "{}CCC", "{}CC(F)(F)F"),
    2: ("{}CCCC{}", "{}COC{}", "{}CC{}", "{}CCO{}", "{}CC(=O)N{}"),
    3: ("{}CC({})C{}", "{}CC({})CC{}"),
}
ALL_BODIES = tuple((body, n_sites)
                   for n_sites, bodies in FRAGMENT_BODIES.items()
                   for body in bodies)


def _assemble(draw, meta_topology, palette, body_of_bead):
    """
    Turn a meta topology plus a per bead choice of fragment body into a
    reference molecule and the permuted copy the extractor is fed.

    `palette` is a list of (body, n_sites); `body_of_bead` maps each meta
    node onto an index into it. Beads sharing an index share a fragname,
    which is what lets the extractor condense them.
    """
    # one label pair per meta edge, so the descriptor matching is forced
    sites = {bead: [] for bead in meta_topology}
    for idx, (low, high) in enumerate(sorted(map(sorted, meta_topology.edges))):
        sites[low].append(f"[>{idx}]")
        sites[high].append(f"[<{idx}]")

    fragments = []
    for bead in meta_topology:
        body, n_sites = palette[body_of_bead[bead]]
        descriptors = sites[bead] + [""] * (n_sites - len(sites[bead]))
        fragments.append(f"#F{bead}=" + body.format(*descriptors))
    fragment_str = "{" + ",".join(fragments) + "}"

    meta_graph = nx.Graph()
    for bead in meta_topology:
        meta_graph.add_node(bead, fragname=f"F{bead}")
    for low, high in meta_topology.edges:
        meta_graph.add_edge(low, high, order=1)

    cg_ref, aa_ref = cgsmiles.MoleculeResolver.from_graph(fragment_str,
                                                          meta_graph,
                                                          legacy=True).resolve()

    # collapse the per bead names onto the shared palette names, exactly as
    # a real force field would reuse one bead type along a chain
    shuffled = aa_ref.copy()
    for atom in shuffled.nodes:
        bead = shuffled.nodes[atom]['fragid'][0]
        shuffled.nodes[atom]['fragname'] = f"B{body_of_bead[bead]}"

    # hypothesis owns the shuffling rather than the `random` module, so a
    # failing ordering is reproducible and shrinkable
    rng = draw(st.randoms(use_true_random=False))
    atoms = sorted(shuffled)
    permuted = list(atoms)
    rng.shuffle(permuted)
    shuffled = nx.relabel_nodes(shuffled, dict(zip(atoms, permuted)), copy=True)

    beads = sorted({bead for atom in shuffled
                    for bead in shuffled.nodes[atom]['fragid']})
    bead_map = dict(zip(beads, draw(st.permutations(beads))))
    for atom in shuffled.nodes:
        shuffled.nodes[atom]['fragid'] = [bead_map[bead] for bead
                                          in shuffled.nodes[atom]['fragid']]

    return {"fragment_str": fragment_str,
            "meta_topology": meta_topology,
            "cg_ref": cg_ref,
            "aa_ref": aa_ref,
            "shuffled": shuffled}


@st.composite
def mapped_molecules(draw, min_beads=2, max_beads=6):
    """
    Draw an arbitrary two resolution molecule: a connected meta graph of
    at most `MAX_SITES` edges per node, possibly with meta level rings,
    whose beads draw their fragments from a small shared palette.
    """
    n_beads = draw(st.integers(min_value=min_beads, max_value=max_beads))
    meta_topology = nx.Graph()
    meta_topology.add_nodes_from(range(n_beads))
    for node in range(1, n_beads):
        parents = [p for p in range(node)
                   if meta_topology.degree(p) < MAX_SITES]
        meta_topology.add_edge(draw(st.sampled_from(parents)), node)

    for _ in range(draw(st.integers(min_value=0, max_value=2))):
        candidates = [(low, high) for low, high in nx.non_edges(meta_topology)
                      if meta_topology.degree(low) < MAX_SITES
                      and meta_topology.degree(high) < MAX_SITES]
        if not candidates:
            break
        meta_topology.add_edge(*draw(st.sampled_from(candidates)))

    max_degree = max(dict(meta_topology.degree).values())
    # the first entry can host the busiest bead, so every bead has at
    # least one admissible body
    palette = [draw(st.sampled_from([entry for entry in ALL_BODIES
                                     if entry[1] >= max_degree]))]
    for _ in range(draw(st.integers(min_value=0, max_value=2))):
        palette.append(draw(st.sampled_from(ALL_BODIES)))

    body_of_bead = {}
    for bead in meta_topology:
        options = [idx for idx, (_, n_sites) in enumerate(palette)
                   if n_sites >= meta_topology.degree(bead)]
        body_of_bead[bead] = draw(st.sampled_from(options))

    return _assemble(draw, meta_topology, palette, body_of_bead)


@st.composite
def homopolymers(draw, min_beads=3, max_beads=6):
    """
    Draw a chain or a ring built from a single repeating two site bead,
    the shape that force fields use for polymers and the one that makes
    the extractor reuse a descriptor label across several meta edges.
    """
    n_beads = draw(st.integers(min_value=min_beads, max_value=max_beads))
    meta_topology = nx.path_graph(n_beads)
    if draw(st.booleans()):
        meta_topology.add_edge(n_beads - 1, 0)
    palette = [(draw(st.sampled_from(FRAGMENT_BODIES[2])), 2)]
    return _assemble(draw, meta_topology, palette,
                     {bead: 0 for bead in meta_topology})


def _wl_hash(molecule):
    """
    Weisfeiler-Lehman hash over element, charge, hcount and bond order.
    Isomorphic graphs always hash equal, so a hash mismatch is a genuine
    failure; the converse does not hold, which is the price for not
    running a VF2 search that can blow up on a long alkane.
    """
    graph = molecule.copy()
    for node in graph.nodes:
        attrs = graph.nodes[node]
        graph.nodes[node]['_wl'] = "{}|{}|{}".format(attrs.get('element'),
                                                     attrs.get('charge'),
                                                     attrs.get('hcount'))
    return nx.weisfeiler_lehman_graph_hash(graph, node_attr='_wl',
                                           edge_attr='order', iterations=4)


def _fingerprint(molecule):
    elements = Counter(molecule.nodes[node].get('element') for node in molecule)
    return (len(molecule),
            nx.number_connected_components(molecule),
            tuple(sorted(elements.items())),
            _wl_hash(molecule))


def _inter_bead_bonds(molecule):
    """
    Count, per pair of beads, the bonds that cross a fragment boundary.
    """
    counts = Counter()
    for low, high in molecule.edges:
        low_ids = set(molecule.nodes[low]['fragid'])
        high_ids = set(molecule.nodes[high]['fragid'])
        if low_ids.isdisjoint(high_ids):
            counts[frozenset(low_ids | high_ids)] += 1
    return counts


SETTINGS = settings(max_examples=200,
                    deadline=None,
                    suppress_health_check=[HealthCheck.too_slow,
                                           HealthCheck.data_too_large])

# The round trip below fails for a known reason, and shrinking a failure
# whose trigger is a node ordering costs far more than the search that
# found it. The `note` output already names the offending strings, so the
# shrink phase buys little here; re-enable it (use SETTINGS) once the
# defect is fixed and the xfail marker comes off.
SETTINGS_NO_SHRINK = settings(SETTINGS, phases=[Phase.explicit,
                                                Phase.reuse,
                                                Phase.generate])

XFAIL_DESCRIPTOR_REUSE = pytest.mark.xfail(
    strict=False,
    reason="known defect: condense_fragments can reuse one descriptor label "
           "for several meta edges, and edges_from_bonding_descrpt then "
           "matches greedily and silently drops the edges it cannot satisfy")


def _check_extractor_roundtrip(case):
    extractor = MoleculeFragmentExtractor()
    cg_new, fragments_new = extractor.get_fragment_dict_from_molecule(case["shuffled"])
    written = write_cgsmiles(cg_new, [fragments_new])
    note(written)

    _, aa_new = cgsmiles.MoleculeResolver.from_string(written, legacy=True).resolve()

    n_ref, n_new = len(case["aa_ref"]), len(aa_new)
    parts_ref = nx.number_connected_components(case["aa_ref"])
    parts_new = nx.number_connected_components(aa_new)
    assert (n_new, parts_new) == (n_ref, parts_ref), (
        f"round trip changed the molecule: {n_ref} atoms in {parts_ref} piece(s) "
        f"became {n_new} atoms in {parts_new} piece(s); a meta edge that finds no "
        f"matching descriptor pair is dropped silently and its dangling valences "
        f"are then filled with hydrogen")
    assert _fingerprint(aa_new) == _fingerprint(case["aa_ref"])


@given(case=mapped_molecules())
@SETTINGS
def test_every_meta_edge_is_resolved(case):
    """
    With one label pair per meta edge the descriptor matching is forced,
    so every meta edge must show up as a bond at the atomistic level and
    the molecule must come out in one piece.
    """
    note(case["fragment_str"])
    _check_extractor_roundtrip(case)

@given(case=mapped_molecules())
@SETTINGS
def test_meta_graph_write_read_roundtrip(case):
    """
    Writing the meta graph out and reading it back must preserve it.
    """
    note(case["fragment_str"])
    _check_extractor_roundtrip(case)
